FROM ghcr.io/alexmspina/base-dev-container:0.0.2

LABEL org.opencontainers.image.source=https://github.com/alexmspina/dev-containers
LABEL org.opencontainers.image.description="Deno 2.3.5 Development Container"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    unzip \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://deno.land/install.sh | sh -s v2.3.5

ENV PATH="$PATH:/root/.deno/bin"

WORKDIR /app

SHELL ["/usr/bin/zsh", "-c"]
CMD ["zsh"]
