FROM ghcr.io/alexmspina/base-dev-container:0.0.1@sha256:c887ecd938d76f672949855fb7f3632ef564ca1517e540c22f5feb0d35c9f2c7

LABEL org.opencontainers.image.source=https://github.com/alexmspina/dev-containers
LABEL org.opencontainers.image.description="Python 3.12 Development Container"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    software-properties-common

RUN add-apt-repository ppa:deadsnakes/ppa

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    python3.13 && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

RUN update-alternatives --install /usr/bin/python python /usr/bin/python3.13 1

RUN curl -fsSL https://starship.rs/install.sh | sh -s -- -y && \
    echo '\neval "$(starship init zsh)"' >> /etc/zsh/zshrc && \
    echo '\neval "$(starship init bash)"' >> /etc/bash.bashrc

COPY starship.toml /root/.config/starship.toml

RUN curl -LsSf https://astral.sh/uv/install.sh | sh && \
    mv ~/.cargo/bin/uv /usr/local/bin/

RUN uv tool install ruff@latest &&  \
    uv add --dev ruff

WORKDIR /app

SHELL ["/usr/bin/zsh", "-c"]
CMD ["zsh"]