FROM ubuntu:noble@sha256:736e224eff152057af468d34e0a495e57e7f70d274a012897d10461527f0ca55

LABEL org.opencontainers.image.source=https://github.com/alexmspina/dev-containers
LABEL org.opencontainers.image.description="Base Development Container"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    git \
    curl \
    zsh \
    ca-certificates \
    fzf \
    ripgrep \
    fd-find \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://starship.rs/install.sh | sh -s -- -y

RUN git clone --depth=1 https://github.com/mattmc3/antidote.git /root/.antidote

COPY zshrc /root/.zshrc
COPY zsh_plugins.txt /root/.zsh_plugins.txt

COPY starship.toml /root/.config/starship.toml

WORKDIR /app

SHELL ["/usr/bin/zsh", "-c"]

CMD [ "zsh" ]
