FROM ubuntu:questing-20250521@sha256:626ac1541d4a0d2f4e71917143b665ebdc252d94f49e73bc2b27dc20ae227390

LABEL org.opencontainers.image.source=https://github.com/alexmspina/dev-containers
LABEL org.opencontainers.image.description="Base Development Container"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    curl \
    zsh \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://starship.rs/install.sh | sh -s -- -y \
    && echo '\neval "$(starship init zsh)"' >> /etc/zsh/zshrc \
    && echo '\neval "$(starship init bash)"' >> /etc/bash.bashrc

COPY starship.toml /root/.config/starship.toml

WORKDIR /app

SHELL ["/usr/bin/zsh", "-c"]

CMD [ "zsh" ]