FROM ubuntu:noble@sha256:dc17125eaac86538c57da886e494a34489122fb6a3ebb6411153d742594c2ddc

LABEL org.opencontainers.image.source=https://github.com/alexmspina/dev-containers
LABEL org.opencontainers.image.description="Base Development Container"

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    git \
    curl \
    zsh \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://starship.rs/install.sh | sh -s -- -y \
    && echo '\neval "$(starship init zsh)"' >> /etc/zsh/zshrc \
    && echo '\neval "$(starship init bash)"' >> /etc/bash.bashrc

COPY starship.toml /root/.config/starship.toml

WORKDIR /app

SHELL ["/usr/bin/zsh", "-c"]

CMD [ "zsh" ]