name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      dockerfile_path:
        description: 'Path to the Dockerfile'
        required: true
        type: string
      image_name:
        description: 'Full image name to push (e.g. ghcr.io/user/image)'
        required: true
        type: string
      semantic_version:
        description: 'Semantic version to tag the image with'
        required: false
        default: 'latest'
        type: string
      context:
        description: 'Build context'
        required: false
        default: '.'
        type: string
    secrets:
      IMAGE_REPO_ACCESS_TOKEN:
        required: true

jobs:
  build-and-push:
    runs-on: ubuntu-24.04-arm

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.IMAGE_REPO_ACCESS_TOKEN }}

      - name: Build and Push Image (Get Digest)
        id: build
        uses: docker/build-push-action@v5
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.dockerfile_path }}
          push: true
          tags: ${{ inputs.image_name }}:${{ inputs.semantic_version }}
          provenance: false
          outputs: type=image,name=${{ inputs.image_name }},push=true
      
      - name: Make GHCR image public
        run: |
          curl -X PATCH \
            -H "Authorization: Bearer ${{ secrets.IMAGE_REPO_ACCESS_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/orgs/${{ github.repository_owner }}/packages/container/{{inputs.image_name}}/visibility \
            -d '{"visibility":"public"}'
