name: Build Image for Base Dev Container

on:
  push:
    branches:
      - main
    paths:
      - 'base/Dockerfile.base'
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/publish-docker-image.yaml
    with:
      dockerfile_path: base/Dockerfile.base
      image_name: base-dev-container
      context: .
      semantic_version: '0.0.1'
    secrets:
      IMAGE_REPO_ACCESS_TOKEN: ${{ secrets.IMAGE_REPO_ACCESS_TOKEN }}
