name: Build Image for Deno 2.3.5 Dev Container

on:
  push:
    branches:
      - main
    paths:
      - 'deno/Dockerfile.deno-2.3.5'
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/publish-docker-image.yaml
    with:
      dockerfile_path: deno/Dockerfile.deno-2.3.5
      image_name: deno-2.3.5-dev-container
      context: .
      semantic_version: '0.0.1'
    secrets:
      IMAGE_REPO_ACCESS_TOKEN: ${{ secrets.IMAGE_REPO_ACCESS_TOKEN }}
