name: Build Image for Base Dev Container

on:
  push:
    branches:
      - main
    paths:
      - 'base/Dockerfile.base'
      - '.github/workflows/publish-base-dev-container.yaml'
      - '.github/workflows/publish-docker-image.yaml'
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/publish-docker-image.yaml
    with:
      dockerfile_path: base/Dockerfile.base
      image_name: ghcr.io/${{ github.repository_owner }}/base-dev-container
      context: base
      platforms: linux/arm64
    secrets:
      IMAGE_REPO_ACCESS_TOKEN: ${{ secrets.IMAGE_REPO_ACCESS_TOKEN }}
