name: Build Image for Deno 2 Dev Container

on:
  push:
    branches:
      - main
    paths:
      - 'supabase-deno/Dockerfile.supabase-deno'
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/publish-docker-image.yaml
    with:
      dockerfile_path: supabase-deno/Dockerfile.supabase-deno
      image_name: supabase-deno-dev-container
      context: .
      semantic_version: '0.0.1'
    secrets:
      IMAGE_REPO_ACCESS_TOKEN: ${{ secrets.IMAGE_REPO_ACCESS_TOKEN }}
