name: Build Image for Base Dev Container

on:
  push:
    branches:
      - main
    paths:
      - './base/Dockerfile.base'
      - '.github/workflows/publish-base-dev-container.yml'
      - '.github/workflows/publish-docker-image.yml'
  workflow_call:

jobs:
  call-reusable:
    uses: ./.github/workflows/publish-docker-image.yml
    with:
      dockerfile_path: base/Dockerfile.base
      image_name: ghcr.io/${{ github.repository_owner }}/base-dev-container
      context: base
