name: Build Image for Go 1.24.3 Dev Container

on:
  push:
    branches:
      - main
    paths:
      - 'go/Dockerfile.go'
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/publish-docker-image.yaml
    with:
      dockerfile_path: go/Dockerfile.go
      image_name: go-1.24.3-dev-container
      context: .
      semantic_version: '0.0.1'
    secrets:
      IMAGE_REPO_ACCESS_TOKEN: ${{ secrets.IMAGE_REPO_ACCESS_TOKEN }}
