name: Build Image for Supabase CLI 2.24.3 with Deno 2.3.5 Dev Container

on:
  push:
    branches:
      - main
    paths:
      - 'supabase-deno/Dockerfile.supabase-cli-2.24.3-deno-2.3.5'
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/publish-docker-image.yaml
    with:
      dockerfile_path: supabase-deno/Dockerfile.supabase-cli-2.24.3-deno-2.3.5
      image_name: supabase-cli-2.24.3-deno-2.3.5-dev-container
      context: .
      semantic_version: '0.0.1'
    secrets:
      IMAGE_REPO_ACCESS_TOKEN: ${{ secrets.IMAGE_REPO_ACCESS_TOKEN }}
