name: Build Image for Python 3.12 Dev Container

on:
  push:
    branches:
      - main
    paths:
      - 'python/Dockerfile.python'
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/publish-docker-image.yaml
    with:
      dockerfile_path: python/Dockerfile.python
      image_name: python-3.12-dev-container
      context: .
      semantic_version: '0.0.1'
    secrets:
      IMAGE_REPO_ACCESS_TOKEN: ${{ secrets.IMAGE_REPO_ACCESS_TOKEN }}
